#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
从管道输入中获取http headers信息,用于判断http工具的默认行为
使用:
    curl -Ss https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending | ./detect_http_headers

    python -c "import requests; print(requests.get('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending').text)"  | ./detect_http_headers

'''
import sys
from bs4 import BeautifulSoup


line_list = []
for line in sys.stdin:
    line_list.append(line)

body = ''.join(line_list)
soup = BeautifulSoup(body)
th_list = soup.find_all('th')
td_list = soup.find_all('td')

for th, td in zip(th_list, td_list):
    print("{}: {}".format(th.get_text(), td.get_text()))
